name: Heroku Deploy
on:
  push:
    branches:
      - 'main'
      - 'deploy'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    # postgres image for API tests via supertest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch complete commit history on all branches
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install
      - name: Seed Database
        run: npm run db:build
      - name: Test Suite
        run: npm run test
        # database url supplied to pg Client constructor, db/client.js
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test-db
      - name: Set Heroku Credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY 
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku Remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        # github.ref_name is the branch name that triggered the workflow
        # you can assign any branch(es) you like in the on: block at the top of this yaml
        # and the ref_name will pick them up
        run: git push heroku ${{ github.ref_name }}:refs/heads/main
